const products = [
  {
    id: 1,
    subject: 'Mathmateics',
    location: 'Block 1, Class 108',
    price: 425,
    space: 6,
    image: 'img/Math.jpg',
    cartquantity: 0,
  },
  {
    id: 2,
    subject: 'English',
    location: 'Block 5, Class 802',
    price: 350,
    space: 4,
    image: 'img/English.jpg',
    cartquantity: 0,
  },
  {
    id: 3,
    subject: 'Football',
    location: 'Block 6, Field 1',
    price: 425,
    space: 8,
    image: 'img/Football.jpg',
    cartquantity: 0,
  },
  {
    id: 4,
    subject: 'History',
    location: 'Block 3, Class 605',
    price: 250,
    space: 6,
    image: 'img/History.jpg',
    cartquantity: 0,
  },
  {
    id: 5,
    subject: 'Geography',
    location: 'Block 1, Geography Lab',
    price: 375,
    space: 5,
    image: 'img/Geography.jpg',
    cartquantity: 0,
  },
  {
    id: 6,
    subject: 'Physics',
    location: 'Block 9, Physics lab',
    price: 300,
    space: 7,
    image: 'img/Physics.jpg',
    cartquantity: 0,
  },
  {
    id: 7,
    subject: 'Chemistry',
    location: 'Block 4, Chemistry Lab',
    price: 250,
    space: 7,
    image: 'img/Chemistry.jpg',
    cartquantity: 0,
  },
  {
    id: 8,
    subject: 'Biology',
    location: 'Block 10, Biology Lab',
    price: 300,
    space: 6,
    image: 'img/Biology.jpg',
    cartquantity: 0,
  },
  {
    id: 9,
    subject: 'Swimming',
    location: 'Block 7, Swimming Pool',
    price: 500,
    space: 9,
    image: 'img/Swimming.jpg',
    cartquantity: 0,
  },
  {
    id: 10,
    subject: 'Lego Robotics',
    location: 'Block 2, Robotics Lab',
    price: 175,
    space: 6,
    image: 'img/Lego.jpg',
    cartquantity: 0,
  },
  {
    id: 11,
    subject: 'Cricket',
    location: 'Block 8, Class 207',
    price: 250,
    space: 9,
    image: 'img/Cricket.jpg',
    cartquantity: 0,
  },
  {
    id: 12,
    subject: 'Computer Science',
    location: 'Block 8, Computer Lab',
    price: 175,
    space: 4,
    image: 'img/ComputerScience.jpg',
    cartquantity: 0,
  },
  {
    id: 13,
    subject: 'Art',
    location: 'Block 5, Art Room',
    price: 250,
    space: 5,
    image: 'img/Art.jpg',
    cartquantity: 0,
  },
  {
    id: 14,
    subject: 'Music',
    location: 'Block 7, Music Room',
    price: 400,
    space: 6,
    image: 'img/Music.jpg',
    cartquantity: 0,
  },
  {
    id: 15,
    subject: 'Dance',
    location: 'Block 7, Dance Studio',
    price: 350,
    space: 4,
    image: 'img/Dance.jpg',
    cartquantity: 0,
  },
];